name: 'Setup Node and AWS Environment'
description: 'Sets up Node.js environment with AWS credentials'
inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
  node-version:
    description: 'Node.js version'
    required: false
    default: '20'
outputs:
  aws-account-id:
    description: 'AWS Account ID retrieved from credentials'
    value: ${{ steps.configure-aws.outputs.aws-account-id }}
  aws-region:
    description: 'AWS Region being used'
    value: ${{ inputs.aws-region }}
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Sets the base and head SHAs required for the nx affected commands in CI
      uses: nrwl/nx-set-shas@v4

    - name: Configure AWS credentials
      id: configure-aws
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
        output-credentials: true
